name: neruwallet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.2
  local_auth_android: ^2.0.8
  local_auth_darwin: ^2.0.3
  
  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Network
  dio: ^5.7.0

  # Local Database
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.6.0+eol

  # Authentication & Social Login
  google_sign_in: ^6.3.0
  supabase_flutter: ^2.8.1

  # Utilities
  equatable: ^2.1.0
  permission_handler: ^13.0.1
  google_fonts: ^8.2.1
  intl: ^0.20.3
  collection: ^1.19.1
  path: ^1.9.1
  path_provider: ^2.1.6
  uuid: ^4.6.0

  # Navigation
  go_router: ^17.5.0

  # UI & Animations
  flutter_svg: ^2.3.0
  smooth_page_indicator: ^2.0.1
  flutter_animate: ^4.5.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^11.0.0
  sign_in_with_apple: ^8.1.0
  flutter_dotenv: ^6.0.1
  
  # Mobile and QR Scanner
  device_info_plus: ^13.2.0
  connectivity_plus: ^7.3.1
  mobile_scanner: ^7.4.0
  qr_flutter: ^4.1.0
  share_plus: ^13.3.0
  flutter_contacts: ^2.1.0
  reorderable_grid_view: ^2.2.8

  # Security Hardening
  flutter_jailbreak_detection: ^1.10.0
  safe_device: ^1.4.1

  # AI & ML Kit
  camera: ^0.12.0+2
  google_mlkit_text_recognition: ^0.16.0
  google_mlkit_face_detection: ^0.14.0
  google_mlkit_commons: ^0.12.0
  google_generative_ai: ^0.4.7
  fl_chart: ^1.2.0

  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  riverpod_generator: ^4.0.3
  drift_dev: ^2.31.0
  json_serializable: ^6.13.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

dependency_overrides:
  path_provider_foundation: 2.4.0
  objective_c: 2.0.0
