// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

Future<Uint8List> processTransactionData({required List<int> data}) =>
    RustLib.instance.api.crateApiProcessTransactionData(data: data);

Future<bool> verifySignature({
  required List<int> publicKey,
  required List<int> message,
  required List<int> signature,
}) => RustLib.instance.api.crateApiVerifySignature(
  publicKey: publicKey,
  message: message,
  signature: signature,
);

class RustSigner {
  const RustSigner();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RustSigner> newInstance() =>
      RustLib.instance.api.crateApiRustSignerNew();

  Future<Uint8List> processTransactionData({required List<int> data}) => RustLib
      .instance
      .api
      .crateApiRustSignerProcessTransactionData(that: this, data: data);

  Future<bool> verifySignature({
    required List<int> publicKey,
    required List<int> message,
    required List<int> signature,
  }) => RustLib.instance.api.crateApiRustSignerVerifySignature(
    that: this,
    publicKey: publicKey,
    message: message,
    signature: signature,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSigner && runtimeType == other.runtimeType;
}
